### ISSUE TITLE
Include more troubleshooting documentation

### ISSUE THREAD

**Issue by xbili** [CS2103JAN2017-W15-B3/main#60]
**Do not close this issue.**

### Common issues faced

- [ ] App runs in background in Gradle `runShadow`
- [ ] Gradle `run` does not build
- [x] Error during compilation `missing tools.jar`

**Comment by lamgj** [comment]
Issue: Error during compilation:"missing tools.jar"
Solution: Reinstall JAVA JDK 1.8
